name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Release]
        platform: [AnyCPU, x86]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --platform ${{ matrix.platform }} --no-restore

    - name: Package
      run: |
        $artifacts = ".\artifacts"
        New-Item -ItemType Directory -Force -Path $artifacts
        Copy-Item "bin\${{ matrix.configuration }}\net8.0\*" -Destination $artifacts -Recurse
        Compress-Archive -Path "$artifacts\*" -DestinationPath ".\UAssetAPI-${{ matrix.platform }}.zip"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UAssetAPI-${{ matrix.platform }}
        path: UAssetAPI-${{ matrix.platform }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          UAssetAPI-AnyCPU/*.zip
          UAssetAPI-x86/*.zip
        generate_release_notes: true
